### ISSUE TITLE
nerves.mk does not get bundled into system tarball

### ISSUE THREAD

**Issue by kfatehi** [nerves-project/nerves-sdk#30]
On a mac, the following happens when sourcing nerves-env.sh

```
$ source nerves-env.sh
grep: /usr/local/opt/nerves-system-bbb/nerves.mk: No such file or directory
Shell environment updated for Nerves ...
```

At first this seemed benign, but it is the cause of https://github.com/nerves-project/nerves-toolchain/issues/3 and https://github.com/nerves-project/nerves-toolchain/issues/4

**Comment by fhunleth** [comment]
Thanks for debugging this. I'm amazed that I got as far as I did on my system without it. Fixed in commit 6002a54f1b027caf1a1ac0ace8f6cecaca7e4a2e.
